# Generated by Django 5.1.5 on 2025-01-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundryApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('kasir', 'Kasir'), ('owner', 'Owner')], default='admin', max_length=20),
        ),
    ]
