# Generated by Django 5.1.5 on 2025-01-19 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundryApp', '0002_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailtransaksi',
            name='transaksi',
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='laundryApp.member'),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='outlet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='laundryApp.outlet'),
        ),
        migrations.AddField(
            model_name='detailtransaksi',
            name='transaksi',
            field=models.ManyToManyField(to='laundryApp.transaksi'),
        ),
    ]
