# Generated by Django 5.1.5 on 2025-01-19 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laundryApp', '0003_remove_detailtransaksi_transaksi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailtransaksi',
            name='qty',
        ),
    ]
